name: compliance tests

on:
  pull_request:
    branches: [ "main" ]


jobs:
  compliance-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: mkmba-nz/github-infra/actions/setup-go@HEAD
      with:
        dockerfile: Dockerfile

    - name: Run tests
      run: go test ./...
